apiVersion: v1          # versi Kubernetes API yang digunakan
kind: Service           # jenis sumber daya yang dibuat, yaitu Service
metadata:               # data informasi untuk identifikasi objek
  name: karsajobs-ui    # nama objek Service
  labels:               # label untuk identifikasi
    app: karsajobs-ui
    tier: frontend
spec:                   # spesifikasi Service yang dibuat
  type: NodePort        # menggunakan tipe NodePort, agar dapat diakses dari luar Cluster melalui port dari setiap Node
  selector:             # mengasosiasikan Pod yang memiliki label tertentu
    app: karsajobs-ui
    tier: frontend
  ports:                # spesifikasi port yang diekspos
  - port: 8000          # port yang di-listen di dalam Cluster
    nodePort: 30010     # port yang di-forward ke port Service (akses dari luar Cluster melalui port ini)